### ISSUE TITLE
API returns HTTP status 200 with invalid token

### ISSUE THREAD

**Issue by TroyMorvant** [exogee-technology/graphweaver#1025]
**Describe the bug**
We have 3 application environments (local, staging, production) and as such we also have 3 tenants in Auth0 that match.  Each tenant has its own clientId, domain, etc.  If I accidentally send a token that was generated from one environment to one of the other environments, GraphWeaver fails to validate the token as expected and correctly refuses to fulfill the request, however the status code that is returned is a 200 and should be 401 or 403 (depending on your interpretation).

Furthermore the body that is returned suggests that the error generated was a 500 (INTERNAL_SERVER_ERROR):

```
"errors": [
        {
            "message": "Authorization context not set",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "complianceSectionDependencyChains"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
```

**To Reproduce**
1. Generate a signed JWT 
2. Make the JWT invalid for any reason (you don't have to have different auth0 tenants, you can just delete a char from the token)
3. Using Postman or Curl send a query to the API by passing the token in the Authorization header 
4. Observe the 200 is returned

**Expected behavior**
- I expect a 401 or 403 to be returned rather than a 200.  
- I expect `extensions.code` to either say `FORBIDDEN` or `UNAUTHORIZED`
- I expect 'message' to contain helpful information that indicates that the token is either invalid, expired, etc

**Actual behavior**
- 200 was returned in the status
- `extensions.code` said `INTERNAL_SERVER_ERROR`
- `message` said `Authorization context not set`

**Screenshots or Screencasts**
If applicable, add screenshots or screencasts to help explain the issue.
<img width="1050" alt="image" src="https://github.com/user-attachments/assets/1d4f266a-a1c0-4a61-806b-89070758e34d">

**Desktop (please complete the following information):**

- OS and version: [e.g. MacOS 13.3.1, Windows 11 v22H2]
MacOS 15.0 Beta

**Additional context**

**Comment by thekevinbrown** [comment]
Hey @TroyMorvant, thanks for the report!

Here's where we're up to on this:

- #1031 has been released, and improves the error message for token validation failures. It also bypasses running resolvers if token validation fails.
- We have not changed the HTTP response code for these errors. [GraphQL does not use HTTP status codes for errors](https://www.apollographql.com/docs/apollo-server/data/errors/#setting-http-status-code-and-headers) because it is possible for responses to partially error, and because the HTTP transport is one transport option amongst many, most of which do not have status codes. Since a response can both partially succeed and partially fail at the same time, clients need to make sure they read payload of the response they get back to know what failed, and if anything failed, what the reason for that was. In this particular case, there are two ways you could go about catching this situation depending on what you want to accomplish.

Option 1: If the response contains an error in the `errors` array that has `extensions.code` of `UNAUTHENTICATED`, then this is the equivalent of a 403 happening in REST. You could check for this on your responses and do what you need.

Option 2: If the response contains an `X-Auth-Redirect` header, that is the server telling the client it needs to go over to a different URL to get authenticated. You can safely intercept this with a check on all responses in your client, and if it's present, redirect to the value in the header. We do this in the admin UI with [an Apollo Link](https://github.com/exogee-technology/graphweaver/blob/8a249433308d599a5dbed88555f55615a932f754/src/packages/admin-ui-components/src/apollo.ts#L42).

I'll go ahead and close this, as there's currently nothing else we're planning to action here, but if I got it wrong don't be afraid to open a new issue or chat on Slack.
