### ISSUE TITLE
Table named 'fish' (among other options that do not pluralise easily) prevents Graphweaver from generating certain CRUD operations

### ISSUE THREAD

**Issue by mackcheesman** [exogee-technology/graphweaver#297]
**Describe the bug**
Due to quirks in the english language, some naming choices in the schemas of my data providers prevent Graphweaver from creating CRUD operations for multiple entities of a given type at once. 

For example, it creates operations such as `createFish, updateFish, deleteFish` and `fish` to operate over a single `Fish` entity, but since one fish is a 'fish', and two or more fish are multiple 'fish', equivalents aren't made for operating on multiple fish.

**To Reproduce**

1. Create a database with a table in it called 'fish' (internal schema is not particularly relevant)
2. Use `graphweaver import` to generate backend logic
3. Run `pnpm build && pnpm start`
4. Access the admin UI
5. Under the data provider, click on the `Fish` table.

**Expected behavior**
As with any other table in my data provider, I should be able to see these entities.

**Actual behavior**
The admin UI produces a 400 error. Using the introspection query reveals that some operations are missing.

**Screenshots or Screencasts**
<img width="1231" alt="Screenshot 2024-01-31 at 10 58 13 am" src="https://github.com/exogee-technology/graphweaver/assets/112445159/caa44d15-5aef-4ec0-8e81-1040b229f89b">

**Desktop (please complete the following information):**

- OS and version: MacOS 14.2.1 (M1)

**Comment by thekevinbrown** [comment]
In the backlog we plan to have a feature to handle this consistently. We should either implement that, or at least make a better error message for developers when `plural(tableName) === tableName`.

**Comment by thekevinbrown** [comment]
The approach we settled on in this PR ^:

* Use the existing `pluralize()` function by default.
* If `pluralize(entityName) === entityName` then use `'multiple'` for the plural instead, e.g. `createFish`, `createMultipleFish`, etc.
* Developers can pass in an option called `plural` like so:
```typescript
@Resolver((of) => Fish)
class FishResolver extends createBaseResolver<Fish, any>(Fish, new BaseDataProvider('fish'), {
	plural: 'fishes',
}) {}
```
* When that option is passed in, we use it instead of the above, e.g. `createFish`, `createFishes`, etc.
* At all times if a collision is detected, we throw an error and refuse to start up so the developer knows what's going on.
